AllCops:
  Exclude:
    - patterns/**/*
    - vendor/bundle/**/*
    - bootstrap/metadata.rb
    - Guardfile
LineLength:
  Max: 160
MethodLength:
  Max: 30
ClassLength:
  Max: 160
CyclomaticComplexity:
  Max: 10
PerceivedComplexity:
  Max: 10
AbcSize:
  Max: 40
Documentation:
  Enabled: false

# TODO: enable later
Style/EachWithObject:
  Enabled: false
Style/ClassVars:
  Enabled: false
